import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hi from "@/components/Hi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ru">
            <body className={`${inter.className} mx-2 mt-2 text-main-text h-[9999px]`}>
                <Hi />
                {children}
            </body>
        </html>
    );
}
